[package]
name = "egg-ast"
version = "0.0.0"
edition = "2021"
rust-version = "1.70.0"

[dependencies]
egg-data = { version = "0.0.0", path = "../egg-data" }
derive_more = "0.99.17"
hex-wrapper = { version = "1.4.1", features = ["serde"] }
