[package]
name = "egg-common-utils"
version = "0.0.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
pipe-trait = "0.4.0"
derive_more = "0.99.17"
command-extra = "1.0.0"
tempfile = "3.5.0"
pretty_assertions = "1.3.0"
