[package]
name = "global-tests"
version = "0.0.0"
edition = "2021"
rust-version = "1.69.0"

[lib]
name = "global_tests"
path = "lib.rs"
doc = false

[dev-dependencies]
pipe-trait = "0.4.0"
pretty_assertions = "1.3.0"
cargo_metadata = "0.15.4"
cargo_toml = "0.15.2"
